## This notebook uses the same pipeline multiple times but for different urls for recipes (apologies for the inconvenience)

In [ ]:
# Install dependencies (run once)
# !pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# -----------------------------
# Configuration
# -----------------------------
BASE_URL = "https://www.bbcgoodfood.com"
COLLECTION_URL = "https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

# -----------------------------
# Functions
# -----------------------------

def get_recipe_links(collection_url):
    """Get all recipe links from a collection page."""
    links = []
    page = 1
    while True:
        url = f"{collection_url}?page={page}"
        print(f"Fetching collection page {page}: {url}")
        res = requests.get(url, headers=headers)
        if res.status_code != 200:
            print("No more pages or failed to fetch collection.")
            break
        soup = BeautifulSoup(res.text, "html.parser")
        recipe_cards = soup.find_all("div", class_="card__section card__content")
        if not recipe_cards:
            break  # No more recipes found
        for card in recipe_cards:
            a_tag = card.find("a", class_="link d-block")
            if a_tag and a_tag.get('href'):
                href = a_tag['href']
                # Only scrape links containing /recipes/
                if "/recipes/" in href:
                    if href.startswith("http"):
                        links.append(href)
                    else:
                        links.append(BASE_URL + href)
        page += 1
        time.sleep(1)  # polite delay
    return links

def scrape_recipe(recipe_url):
    """Scrape a single recipe page for title, ingredients, and nutrition info."""
    print(f"Scraping recipe: {recipe_url}")
    res = requests.get(recipe_url, headers=headers)
    soup = BeautifulSoup(res.text, "html.parser")
    
    # Title
    title_tag = soup.find("h1", class_="post-header__title")
    title = title_tag.text.strip() if title_tag else "No title"
    
    # Ingredients
    ingredients = []
    tabbed_div = soup.find("div", class_="tabbed-list__content")
    if tabbed_div:
        ul_list = tabbed_div.find("ul", class_="ingredients-list")
        if ul_list:
            for li in ul_list.find_all("li", class_="ingredients-list__item"):
                qty_tag = li.find("span", class_="ingredients-list__item-quantity")
                ing_tag = li.find("span", class_="ingredients-list__item-ingredient")
                note_tag = li.find("div", class_="ingredients-list__item-note")
                
                qty = qty_tag.text.strip() if qty_tag else ""
                ingredient = ing_tag.text.strip() if ing_tag else ""
                note = note_tag.text.strip() if note_tag else ""
                
                ingredients.append({
                    "quantity": qty,
                    "ingredient": ingredient,
                    "note": note
                })
    
    # Nutrition
    nutrition = {}
    nutrition_list = soup.find("ul", class_="nutrition-list")
    if nutrition_list:
        for li in nutrition_list.find_all("li", class_="nutrition-list__item"):
            label_tag = li.find("span", class_="nutrition-list__label")
            if label_tag:
                label = label_tag.text.strip()
                # Some values may have extra divs, use first text after label
                value = li.get_text(separator="|").split("|")[1].strip() if "|" in li.get_text(separator="|") else ""
                nutrition[label] = value
    
    return {
        "title": title,
        "url": recipe_url,
        "ingredients": ingredients,
        "nutrition": nutrition
    }

def scrape_collection(collection_url):
    """Scrape all recipes from a collection."""
    recipe_links = get_recipe_links(collection_url)
    print(f"Found {len(recipe_links)} recipe links.")
    all_recipes = []
    
    for idx, link in enumerate(recipe_links, 1):
        try:
            recipe_data = scrape_recipe(link)
            all_recipes.append(recipe_data)
            time.sleep(1)  # polite delay
        except Exception as e:
            print(f"Failed to scrape {link}: {e}")
    
    return all_recipes

# -----------------------------
# Run the scraper
# -----------------------------
recipes = scrape_collection(COLLECTION_URL)

# -----------------------------
# Save to CSV
# -----------------------------
data_for_csv = []
for r in recipes:
    for ing in r['ingredients']:
        data_for_csv.append({
            "title": r['title'],
            "url": r['url'],
            "ingredient": ing['ingredient'],
            "quantity": ing['quantity'],
            "note": ing['note'],
            **r['nutrition']  # include all nutrition info as columns
        })

df = pd.DataFrame(data_for_csv)
df.to_csv("bbc_goodfood_recipes.csv", index=False)
print("Scraping complete! Data saved to bbc_goodfood_recipes.csv")

Fetching collection page 1: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=1
Fetching collection page 2: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=2
Fetching collection page 3: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=3
Fetching collection page 4: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=4
Fetching collection page 5: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=5
Fetching collection page 6: https://www.bbcgoodfood.com/recipes/collection/quick-and-easy-family-recipes?page=6
No more pages or failed to fetch collection.
Found 95 recipe links.
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-chicken-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/pasta-salmon-peas
Scraping recipe: https://www.bbcgoodfood.com/recipes/oriental-egg-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-fish-fingers
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheese-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/spiced-carrot-lentil-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/speedy-sausage-stroganoff-tagliatelle
Scraping recipe: https://www.bbcgoodfood.com/recipes/honey-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-teriyaki-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pot-mushroom-potato-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/mustard-stuffed-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-thai-prawn-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/crispy-sesame-lemon-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/smash-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/fish-tacos-2
Scraping recipe: https://www.bbcgoodfood.com/recipes/nutty-chicken-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-salmon-burgers-spicy-mayo
Scraping recipe: https://www.bbcgoodfood.com/recipes/green-chicken-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/falafel-burgers-0
Scraping recipe: https://www.bbcgoodfood.com/recipes/easiest-ever-paella
Scraping recipe: https://www.bbcgoodfood.com/recipes/tuna-sundried-tomato-pasta-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/spanish-rice-prawn-one-pot
Scraping recipe: https://www.bbcgoodfood.com/recipes/lamb-meatballs-green-tahini-tabbouleh
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-chicken-thighs
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-meatballs
Scraping recipe: https://www.bbcgoodfood.com/recipes/gnocchi-roasted-red-pepper-sauce
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-pork-chops
Scraping recipe: https://www.bbcgoodfood.com/recipes/baked-cod-with-creamy-mushroom-leek-orzo
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-easy-korean-pork
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-black-bean-tacos
Scraping recipe: https://www.bbcgoodfood.com/recipes/super-quick-fish-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/bang-bang-chicken-vegetable-noodles
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-sweet-sour-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-courgette-bacon-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-ham-leek-mushroom-spaghetti
Scraping recipe: https://www.bbcgoodfood.com/recipes/greek-style-beans
Scraping recipe: https://www.bbcgoodfood.com/recipes/mushroom-risotto
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-baked-potatoes
Scraping recipe: https://www.bbcgoodfood.com/recipes/fastest-ever-lemon-pudding
Scraping recipe: https://www.bbcgoodfood.com/recipes/german-cheese-bacon-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/anytime-pesto-prawn-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-sausages
Scraping recipe: https://www.bbcgoodfood.com/recipes/crispy-meatball-pizza
Scraping recipe: https://www.bbcgoodfood.com/recipes/thai-prawn-noodles
Scraping recipe: https://www.bbcgoodfood.com/recipes/salmon-fish-finger-sandwich
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-leek-fennel-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/halloumi-bulghar-chickpea-rocket-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-sausage-bean-one-pot
Scraping recipe: https://www.bbcgoodfood.com/recipes/broccoli-green-beans-toasted-hazelnut-butter
Scraping recipe: https://www.bbcgoodfood.com/recipes/peanut-butter-noodles-with-tofu-veg
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheesy-bean-chipotle-quesadillas
Scraping recipe: https://www.bbcgoodfood.com/recipes/butter-bean-chorizo-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/secret-green-sauce-spaghetti
Scraping recipe: https://www.bbcgoodfood.com/recipes/asparagus-meatball-orzo
Scraping recipe: https://www.bbcgoodfood.com/recipes/italian-stuffed-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-lamb-biryani
Scraping recipe: https://www.bbcgoodfood.com/recipes/chickpea-coriander-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-sweetcorn-egg-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/spring-meatball-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pan-chicken-couscous
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-chicken-chasseur
Scraping recipe: https://www.bbcgoodfood.com/recipes/build-your-own-pesto-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/salmon-broccoli-potato-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/help-yourself-tuna-rice-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-linguine-ham-lemon-basil
Scraping recipe: https://www.bbcgoodfood.com/recipes/summer-winter-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/hoisin-mackerel-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/hob-table-moussaka
Scraping recipe: https://www.bbcgoodfood.com/recipes/fridge-raid-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/tomato-basil-sauce
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-pizza-dough-2
Scraping recipe: https://www.bbcgoodfood.com/recipes/beef-rissoles
Scraping recipe: https://www.bbcgoodfood.com/recipes/coconut-fish-curry-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/tofu-stir-fry
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-hummus-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/gnocchi-fish-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/singapore-noodles
Scraping recipe: https://www.bbcgoodfood.com/recipes/honey-sesame-orange-king-prawns
Scraping recipe: https://www.bbcgoodfood.com/recipes/15-minute-chicken-halloumi-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/swedish-meatball-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/teriyaki-salmon-green-beans
Scraping recipe: https://www.bbcgoodfood.com/recipes/crispy-chicken-strips
Scraping recipe: https://www.bbcgoodfood.com/recipes/simple-stir-fry
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-veg-bowl
Scraping recipe: https://www.bbcgoodfood.com/recipes/potato-pea-egg-curry-rotis
Scraping recipe: https://www.bbcgoodfood.com/recipes/carbonara-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/pork-apple-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/orzo-tomato-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-fajitas
Scraping recipe: https://www.bbcgoodfood.com/recipes/southern-fried-chicken-tacos
Scraping recipe: https://www.bbcgoodfood.com/recipes/healthier-veggie-carbonara
Scraping recipe: https://www.bbcgoodfood.com/recipes/salmon-egg-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/blackened-salmon-fajitas
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheesy-ham-broccoli-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/spaghetti-aglio-e-olio-with-crispy-bacon
Scraping complete! Data saved to bbc_goodfood_recipes.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"bbc_goodfood_recipes.csv")

df.head()

df["title"] = (
    df["url"]
    .str.split("/")
    .str[-1]
    .str.replace("-", " ")
    .str.title()
)

df[["title","url"]].head()

df["ingredient_full"] = (
    df["quantity"].fillna("") + " " +
    df["ingredient"].fillna("") + " " +
    df["note"].fillna("")
).str.strip()

ingredients_grouped = (
    df.groupby("url")["ingredient_full"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

ingredients_grouped.head()

nutrition_cols = [
    "kcal","fat","saturates","carbs",
    "sugars","fibre","protein","salt"
]

recipes = (
    df.groupby("url")
    .first()
    .reset_index()[["url","title"] + nutrition_cols]
)

recipes.head()

clean_df2 = recipes.merge(
    ingredients_grouped,
    on="url",
    how="left"
)

clean_df2.head()

clean_df2 = clean_df2.rename(columns={
    "ingredient_full":"ingredients"
})

cols = ["fat","saturates","carbs","sugars","fibre","protein","salt"]

for col in cols:
    clean_df2[col] = (
        clean_df2[col]
        .astype(str)
        .str.replace(r'(low|medium|high)', '', regex=True)  # remove labels
        .str.extract(r'([\d\.]+)')[0]                       # keep number
        .fillna('')
        + "g"                                               # add grams back
    )
    # Chat wrote this code for cleaning the dataset (title uses the last words of the url, ingredients combines quantity, ingredient and note
    # nutrition removes low/medium/high labels and keeps only numbers with 'g' unit for grams (remove random words like 16glow instead of 16g ))
clean_df2.to_csv(r"bbc_quick_and_easy_recipes.csv", index=False)

In [32]:
clean_df2.head()

,url,title,kcal,fat,saturates,carbs,sugars,fibre,protein,salt,ingredients
0,https://www.bbcgoodfood.com/recipes/15-minute-...,15 Minute Chicken Halloumi Burgers,737,42.0g,10.0g,49.0g,6.0g,4.0g,39g,4.1g,"2 chicken breast fillets, 1 tbsp oil plus extr..."
1,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Baked Potatoes,206,2.0g,0.4g,40.0g,3.0g,5.0g,5g,0.01g,"4 baking potatoes (about 250g each), ½ tbsp su..."
2,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Chicken Thighs,111,8.0g,2.0g,0.0g,0.0g,0.3g,11g,0.7g,"1 tsp paprika, ½ tsp mixed herbs, ½ tsp garlic..."
3,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Fish Fingers,64,1.0g,0.2g,7.0g,0.2g,0.3g,7g,0.7g,"250g white fish loin, 1 egg beaten, 75g panko ..."
4,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Meatballs,82,6.0g,2.0g,2.0g,0.4g,0.3g,6g,0.18g,"4 good-quality sausages, 500g beef mince, ½ on..."

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# -----------------------------
# Configuration
# -----------------------------
BASE_URL = "https://www.bbcgoodfood.com"
COLLECTION_URL = "https://www.bbcgoodfood.com/recipes/collection/batch-cooking-recipes"

headers = {
    "User-Agent": "Mozilla/5.0"
}

# -----------------------------
# 1. Get recipe links
# -----------------------------
def get_recipe_links(collection_url):
    links = []
    page = 1

    while True:
        url = f"{collection_url}?page={page}"
        print(f"Fetching page {page}...")

        res = requests.get(url, headers=headers)
        if res.status_code != 200:
            break

        soup = BeautifulSoup(res.text, "html.parser")

        cards = soup.find_all("div", class_="card__section card__content")

        if not cards:
            break

        for card in cards:
            a = card.find("a", href=True)
            if a:
                href = a["href"]
                if "/recipes/" in href:
                    full_url = href if href.startswith("http") else BASE_URL + href
                    if full_url not in links:
                        links.append(full_url)

        page += 1
        time.sleep(1)

    return links


# -----------------------------
# 2. Scrape each recipe
# -----------------------------
def scrape_recipe(url):
    print(f"Scraping: {url}")

    res = requests.get(url, headers=headers)
    soup = BeautifulSoup(res.text, "html.parser")

    # ---- TITLE ----
    title_tag = soup.find("h1")
    title = title_tag.get_text(strip=True) if title_tag else "No title"

    # ---- INGREDIENTS ----
    ingredients = []
    for li in soup.select("li.ingredients-list__item"):
        qty = li.select_one(".ingredients-list__item-quantity")
        ing = li.select_one(".ingredients-list__item-ingredient")
        note = li.select_one(".ingredients-list__item-note")

        quantity = qty.get_text(strip=True) if qty else ""
        ingredient = ing.get_text(strip=True) if ing else ""
        note_text = note.get_text(strip=True) if note else ""

        ingredients.append({
            "quantity": quantity,
            "ingredient": ingredient,
            "note": note_text
        })

    # ---- NUTRITION ----
    nutrition = {}
    for li in soup.select("ul.nutrition-list li"):
        label = li.select_one(".nutrition-list__label")
        if label:
            key = label.get_text(strip=True)
            value = li.get_text(strip=True).replace(key, "").strip()
            nutrition[key] = value

    return {
        "title": title,
        "url": url,
        "ingredients": ingredients,
        "nutrition": nutrition
    }


# -----------------------------
# 3. Scrape full collection
# -----------------------------
def scrape_collection(collection_url):
    recipe_links = get_recipe_links(collection_url)
    print(f"\nFound {len(recipe_links)} recipes\n")

    all_data = []

    for i, link in enumerate(recipe_links, 1):
        try:
            data = scrape_recipe(link)
            all_data.append(data)
            print(f"[{i}/{len(recipe_links)}] Done: {data['title']}")
            time.sleep(1)
        except Exception as e:
            print(f"Error on {link}: {e}")

    return all_data


# -----------------------------
# 4. Run scraper
# -----------------------------
recipes = scrape_collection(COLLECTION_URL)

# -----------------------------
# 5. Convert to CSV
# -----------------------------
rows = []

for r in recipes:
    for ing in r["ingredients"]:
        row = {
            "title": r["title"],
            "url": r["url"],
            "ingredient": ing["ingredient"],
            "quantity": ing["quantity"],
            "note": ing["note"]
        }

        # Add nutrition fields dynamically
        for k, v in r["nutrition"].items():
            row[k] = v

        rows.append(row)

df = pd.DataFrame(rows)

In [ ]:
# Save the already scraped DataFrame safely

# Option 1: save to your folder (fixed path)
df = df.to_csv(r"bbc_batch_cooking_recipes.csv", index=False)

print("✅ File saved successfully!")

✅ File saved successfully!

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"bbc_batch_cooking_recipes.csv")

df.head()

df["title"] = (
    df["url"]
    .str.split("/")
    .str[-1]
    .str.replace("-", " ")
    .str.title()
)

df[["title","url"]].head()

df["ingredient_full"] = (
    df["quantity"].fillna("") + " " +
    df["ingredient"].fillna("") + " " +
    df["note"].fillna("")
).str.strip()

ingredients_grouped = (
    df.groupby("url")["ingredient_full"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

ingredients_grouped.head()

nutrition_cols = [
    "kcal","fat","saturates","carbs",
    "sugars","fibre","protein","salt"
]

recipes = (
    df.groupby("url")
    .first()
    .reset_index()[["url","title"] + nutrition_cols]
)

recipes.head()

clean_df = recipes.merge(
    ingredients_grouped,
    on="url",
    how="left"
)

clean_df.head()

clean_df = clean_df.rename(columns={
    "ingredient_full":"ingredients"
})

cols = ["fat","saturates","carbs","sugars","fibre","protein","salt"]

for col in cols:
    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(r'(low|medium|high)', '', regex=True)  # remove labels
        .str.extract(r'([\d\.]+)')[0]                       # keep number
        .fillna('')
        + "g"                                               # add grams back
    )
    # Chat wrote this code for cleaning the dataset (title uses the last words of the url, ingredients combines quantity, ingredient and note
    # nutrition removes low/medium/high labels and keeps only numbers with 'g' unit for grams (remove random words like 16glow instead of 16g ))
clean_df.to_csv("bbc_batch_cooking_recipes.csv", index=False)
clean_df.head()

,url,title,kcal,fat,saturates,carbs,sugars,fibre,protein,salt,ingredients
0,https://www.bbcgoodfood.com/recipes/apple-pear...,Apple Pear Cherry Compote,199,1g,0g,51g,47g,4g,1g,0.03g,"8 eating apples peeled, cored and cut into chu..."
1,https://www.bbcgoodfood.com/recipes/aubergine-...,Aubergine Parmigiana Lasagne,466,23g,9g,41g,12g,7g,20g,0.6g,3 large aubergines trimmed and thinly sliced l...
2,https://www.bbcgoodfood.com/recipes/balsamic-s...,Balsamic Steaks Peppercorn Wedges,534,25g,8g,43g,4g,5g,34g,0.3g,"2 tbsp balsamic vinegar, 2 tsp concentrated li..."
3,https://www.bbcgoodfood.com/recipes/basic-lentils,Basic Lentils,230,5g,3g,31g,4g,5g,13g,0.1g,"2 tbsp coconut oil, 2 onions chopped, 4 garlic..."
4,https://www.bbcgoodfood.com/recipes/bean-sausa...,Bean Sausage Hotpot,474,23g,8g,39g,10g,9g,29g,3.55g,8 large sausages (course-cut ones like Toulous...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# -----------------------------
# Configuration
# -----------------------------
BASE_URL = "https://www.bbcgoodfood.com"
COLLECTION_URL = "https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

# -----------------------------
# Functions
# -----------------------------
def get_recipe_links(collection_url):
    """Get all recipe links from a collection page."""
    links = []
    page = 1
    while True:
        url = f"{collection_url}?page={page}"
        print(f"Fetching collection page {page}: {url}")
        res = requests.get(url, headers=headers)
        if res.status_code != 200:
            print("No more pages or failed to fetch collection.")
            break
        soup = BeautifulSoup(res.text, "html.parser")
        recipe_cards = soup.find_all("div", class_="card__section card__content")
        if not recipe_cards:
            break  # No more recipes found
        for card in recipe_cards:
            a_tag = card.find("a", class_="link d-block")
            if a_tag and a_tag.get('href'):
                href = a_tag['href']
                if "/recipes/" in href:
                    if href.startswith("http"):
                        links.append(href)
                    else:
                        links.append(BASE_URL + href)
        page += 1
        time.sleep(1)
    return links

def scrape_recipe(recipe_url):
    """Scrape a single recipe page for title, ingredients, and nutrition info."""
    print(f"Scraping recipe: {recipe_url}")
    res = requests.get(recipe_url, headers=headers)
    soup = BeautifulSoup(res.text, "html.parser")
    
    # Title
    title_tag = soup.find("h1", class_="post-header__title")
    title = title_tag.text.strip() if title_tag else "No title"
    
    # Ingredients
    ingredients = []
    tabbed_div = soup.find("div", class_="tabbed-list__content")
    if tabbed_div:
        ul_list = tabbed_div.find("ul", class_="ingredients-list")
        if ul_list:
            for li in ul_list.find_all("li", class_="ingredients-list__item"):
                qty_tag = li.find("span", class_="ingredients-list__item-quantity")
                ing_tag = li.find("span", class_="ingredients-list__item-ingredient")
                note_tag = li.find("div", class_="ingredients-list__item-note")
                qty = qty_tag.text.strip() if qty_tag else ""
                ingredient = ing_tag.text.strip() if ing_tag else ""
                note = note_tag.text.strip() if note_tag else ""
                ingredients.append({"quantity": qty, "ingredient": ingredient, "note": note})
    
    # Nutrition
    nutrition = {}
    nutrition_list = soup.find("ul", class_="nutrition-list")
    if nutrition_list:
        for li in nutrition_list.find_all("li", class_="nutrition-list__item"):
            label_tag = li.find("span", class_="nutrition-list__label")
            if label_tag:
                label = label_tag.text.strip()
                value = li.get_text(separator="|").split("|")[1].strip() if "|" in li.get_text(separator="|") else ""
                nutrition[label] = value
    
    return {"title": title, "url": recipe_url, "ingredients": ingredients, "nutrition": nutrition}

def scrape_collection(collection_url):
    """Scrape all recipes from a collection."""
    recipe_links = get_recipe_links(collection_url)
    print(f"Found {len(recipe_links)} recipe links.")
    all_recipes = []
    for idx, link in enumerate(recipe_links, 1):
        try:
            recipe_data = scrape_recipe(link)
            all_recipes.append(recipe_data)
            time.sleep(1)
        except Exception as e:
            print(f"Failed to scrape {link}: {e}")
    return all_recipes

# -----------------------------
# Run the scraper
# -----------------------------
recipes = scrape_collection(COLLECTION_URL)

# -----------------------------
# Save to CSV
# -----------------------------
data_for_csv = []
for r in recipes:
    for ing in r['ingredients']:
        data_for_csv.append({
            "title": r['title'],
            "url": r['url'],
            "ingredient": ing['ingredient'],
            "quantity": ing['quantity'],
            "note": ing['note'],
            **r['nutrition']
        })

df = pd.DataFrame(data_for_csv)
df.to_csv(r"dinner_recipes.csv", index=False)
print("Scraping complete! Data saved to dinner_recipes.csv")

Fetching collection page 1: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=1
Fetching collection page 2: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=2
Fetching collection page 3: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=3
Fetching collection page 4: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=4
Fetching collection page 5: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=5
Fetching collection page 6: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=6
Fetching collection page 7: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=7
Fetching collection page 8: https://www.bbcgoodfood.com/recipes/collection/easy-dinner-recipes?page=8
No more pages or failed to fetch collection.
Found 142 recipe links.
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-pasta-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-chicken-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-ragu
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-pesto-kale-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/fish-pie-mac-n-cheese
Scraping recipe: https://www.bbcgoodfood.com/recipes/speedy-lentil-coconut-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/fajita-style-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-garlic-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/meatball-black-bean-chilli
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-salmon-leek-potato-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-chickpea-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-sausage-casserole
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-leek-brown-rice-stir-fry
Scraping recipe: https://www.bbcgoodfood.com/recipes/gnocchi-cacio-e-pepe
Scraping recipe: https://www.bbcgoodfood.com/recipes/roasted-carrot-whipped-feta-tart
Scraping recipe: https://www.bbcgoodfood.com/recipes/bean-halloumi-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-yaki-udon
Scraping recipe: https://www.bbcgoodfood.com/recipes/piri-piri-chicken-smashed-sweet-potatoes-broccoli
Scraping recipe: https://www.bbcgoodfood.com/recipes/roasted-cauliflower-chickpea-coconut-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/paneer-korma
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-tikka-masala
Scraping recipe: https://www.bbcgoodfood.com/recipes/cowboy-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-chicken-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/manchurian-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausages-with-lemon-rosemary-roast-potatoes
Scraping recipe: https://www.bbcgoodfood.com/recipes/fajita-chicken-rice-bowl-with-burnt-lime
Scraping recipe: https://www.bbcgoodfood.com/recipes/sichuan-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-ginger-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/miso-butternut-squash-ramen
Scraping recipe: https://www.bbcgoodfood.com/recipes/slow-cooker-lamb-shoulder
Scraping recipe: https://www.bbcgoodfood.com/recipes/pork-souvlaki
Scraping recipe: https://www.bbcgoodfood.com/recipes/vegan-squash-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/caramelised-red-onion-anchovy-pasta-with-gremolata
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-vegetable-lasagne
Scraping recipe: https://www.bbcgoodfood.com/recipes/spaghetti-puttanesca
Scraping recipe: https://www.bbcgoodfood.com/recipes/thai-curry-noodle-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-chicken-rice-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/green-goddess-bowl-with-crispy-sesame-tofu
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-halloumi-tomato-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/feel-good-pasta-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-tofu-curry-with-homemade-roti
Scraping recipe: https://www.bbcgoodfood.com/recipes/broccoli-stem-falafel-bowl
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pot-cheeseburger-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/satay-sweet-potato-curry
Scraping recipe: https://www.bbcgoodfood.com/recipes/meatball-tomato-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/black-bean-tortilla-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-burrito
Scraping recipe: https://www.bbcgoodfood.com/recipes/orzo-chickpea-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/sticky-lemon-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/confit-salmon-with-tahini-pistachio-herb-crust
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-soy-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/roasted-vegetable-soup-with-halloumi-croutons
Scraping recipe: https://www.bbcgoodfood.com/recipes/fish-tacos-2
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-tofu-tahini-noodle-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/crispy-shredded-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/harissa-fish-with-bulgur-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-sausage-squash-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-chorizo-ragu
Scraping recipe: https://www.bbcgoodfood.com/recipes/currywurst
Scraping recipe: https://www.bbcgoodfood.com/recipes/thai-inspired-coconut-chicken-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/tomato-mascarpone-risotto
Scraping recipe: https://www.bbcgoodfood.com/recipes/salmon-asparagus-one-pot-gratin
Scraping recipe: https://www.bbcgoodfood.com/recipes/potato-leek-chorizo-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pot-five-spice-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/microwave-cheats-paella
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-sweet-potato-jackets-with-tahini-yogurt
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-crispy-chilli-beef
Scraping recipe: https://www.bbcgoodfood.com/recipes/potato-hash-with-greens
Scraping recipe: https://www.bbcgoodfood.com/recipes/herby-fish-fingers-chinese-style-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/pork-chop-with-creamy-leeks
Scraping recipe: https://www.bbcgoodfood.com/recipes/oven-baked-pork-chops
Scraping recipe: https://www.bbcgoodfood.com/recipes/sumac-turkey-stuffed-pittas
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-scale-cheesy-fish-pie-kale
Scraping recipe: https://www.bbcgoodfood.com/recipes/mustard-parmesan-crumbed-chicken
Scraping recipe: https://www.bbcgoodfood.com/recipes/halloumi-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/pulled-pork-tacos-pineapple-salsa
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-venison-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/salmon-risotto
Scraping recipe: https://www.bbcgoodfood.com/recipes/pork-chops-mustardy-butter-beans
Scraping recipe: https://www.bbcgoodfood.com/recipes/vegetable-pasta-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/chilli-bean-guacamole-topped-chips
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheesy-ham-hock-spinach-ricotta-lasagne
Scraping recipe: https://www.bbcgoodfood.com/recipes/fragrant-lemongrass-coconut-chicken-stir-fry
Scraping recipe: https://www.bbcgoodfood.com/recipes/big-batch-lamb-stew
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pan-roast-rack-of-lamb-green-olive-potatoes
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pot-tomato-orzo
Scraping recipe: https://www.bbcgoodfood.com/recipes/gnocchi-fish-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/pasta-salmon-peas
Scraping recipe: https://www.bbcgoodfood.com/recipes/meatball-garlic-bread-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/chipotle-chicken-slaw
Scraping recipe: https://www.bbcgoodfood.com/recipes/spinach-chilli-bean-pide
Scraping recipe: https://www.bbcgoodfood.com/recipes/mince-tatties
Scraping recipe: https://www.bbcgoodfood.com/recipes/roast-chicken-squashed-new-potatoes-cheesy-creamed-spinach
Scraping recipe: https://www.bbcgoodfood.com/recipes/spiced-salmon-tomato-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/fish-chip-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/broccoli-pesto-pancetta-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/thai-noodle-soup-salmon
Scraping recipe: https://www.bbcgoodfood.com/recipes/ravioli-lasagne
Scraping recipe: https://www.bbcgoodfood.com/recipes/mexican-style-stuffed-peppers
Scraping recipe: https://www.bbcgoodfood.com/recipes/summer-roast-chicken-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/punjabi-partha
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-steak-cajun-potatoes-spicy-slaw
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-harissa-spaghetti
Scraping recipe: https://www.bbcgoodfood.com/recipes/olive-cauliflower-harissa-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-leek-mash-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-cheesy-mustard-toad-hole-broccoli
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pan-thai-green-salmon
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-cacciatore-one-pot-orzo
Scraping recipe: https://www.bbcgoodfood.com/recipes/pineapple-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/singapore-noodles
Scraping recipe: https://www.bbcgoodfood.com/recipes/bulgur-aubergine-pilaf
Scraping recipe: https://www.bbcgoodfood.com/recipes/vegan-meatballs
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-fried-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/healthy-tikka-masala
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-chicken-bean-leek-traybake
Scraping recipe: https://www.bbcgoodfood.com/recipes/chipotle-chicken-tinga
Scraping recipe: https://www.bbcgoodfood.com/recipes/nduja-lasagne
Scraping recipe: https://www.bbcgoodfood.com/recipes/no-cook-veggie-fajitas
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-pulled-aubergine-black-bean-tacos
Scraping recipe: https://www.bbcgoodfood.com/recipes/baked-salmon
Scraping recipe: https://www.bbcgoodfood.com/recipes/curried-prawn-green-bean-pie
Scraping recipe: https://www.bbcgoodfood.com/recipes/tomato-spinach-kitchari
Scraping recipe: https://www.bbcgoodfood.com/recipes/swedish-meatball-burgers
Scraping recipe: https://www.bbcgoodfood.com/recipes/scandi-style-flatbread
Scraping recipe: https://www.bbcgoodfood.com/recipes/roast-dinner-one
Scraping recipe: https://www.bbcgoodfood.com/recipes/spaghetti-with-tomatoes-walnuts
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-mushroom-ragu
Scraping recipe: https://www.bbcgoodfood.com/recipes/aubergine-halloumi-harissa-skillet-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-mushroom-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-crushed-harissa-chickpeas
Scraping recipe: https://www.bbcgoodfood.com/recipes/gluten-free-salmon-pasta
Scraping recipe: https://www.bbcgoodfood.com/recipes/elote-inspired-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/cajun-prawn-charred-corn-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/chickpea-tagine-couscous
Scraping recipe: https://www.bbcgoodfood.com/recipes/tandoori-style-lamb-chops
Scraping recipe: https://www.bbcgoodfood.com/recipes/broad-bean-pea-ricotta-frittata
Scraping recipe: https://www.bbcgoodfood.com/recipes/courgette-chilli-mint-with-pearl-couscous
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-black-bean-tacos
Scraping recipe: https://www.bbcgoodfood.com/recipes/tomato-black-bean-taco-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-bhuna
Scraping recipe: https://www.bbcgoodfood.com/recipes/tasty-turkey-meatballs
Scraping recipe: https://www.bbcgoodfood.com/recipes/vegan-winter-one-pan
Scraping complete! Data saved to dinner_recipes.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"dinner_recipes.csv")

df.head()

df["title"] = (
    df["url"]
    .str.split("/")
    .str[-1]
    .str.replace("-", " ")
    .str.title()
)

df[["title","url"]].head()

df["ingredient_full"] = (
    df["quantity"].fillna("") + " " +
    df["ingredient"].fillna("") + " " +
    df["note"].fillna("")
).str.strip()

ingredients_grouped = (
    df.groupby("url")["ingredient_full"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

ingredients_grouped.head()

nutrition_cols = [
    "kcal","fat","saturates","carbs",
    "sugars","fibre","protein","salt"
]

recipes = (
    df.groupby("url")
    .first()
    .reset_index()[["url","title"] + nutrition_cols]
)

recipes.head()

clean_df = recipes.merge(
    ingredients_grouped,
    on="url",
    how="left"
)

clean_df.head()

clean_df = clean_df.rename(columns={
    "ingredient_full":"ingredients"
})

cols = ["fat","saturates","carbs","sugars","fibre","protein","salt"]

for col in cols:
    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(r'(low|medium|high)', '', regex=True)  # remove labels
        .str.extract(r'([\d\.]+)')[0]                       # keep number
        .fillna('')
        + "g"                                               # add grams back
    )
    # Chat wrote this code for cleaning the dataset (title uses the last words of the url, ingredients combines quantity, ingredient and note
    # nutrition removes low/medium/high labels and keeps only numbers with 'g' unit for grams (remove random words like 16glow instead of 16g ))
clean_df.to_csv("dinner_recipes.csv", index=False)
clean_df.head()

,url,title,kcal,fat,saturates,carbs,sugars,fibre,protein,salt,ingredients
0,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Crispy Chilli Beef,440.0,19.0g,3.0g,34g,20.0g,3.0g,31.0g,3.1g,250g thin-cut minute steak thinly sliced into ...
1,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Sweet Potato Jackets With Tahini Yogurt,581.0,30.0g,9.0g,59g,34.0g,1.0g,12.0g,0.4g,"2 sweet potatoes, 1 tbsp olive oil plus 2 tsp,..."
2,https://www.bbcgoodfood.com/recipes/aubergine-...,Aubergine Halloumi Harissa Skillet Bake,546.0,39.0g,20.0g,15g,14.0g,7.0g,31.0g,3.5g,"2-4 tbsp olive oil plus a drizzle, 1 large aub..."
3,https://www.bbcgoodfood.com/recipes/baked-salmon,Baked Salmon,354.0,23.0g,4.0g,1g,0.2g,0.4g,35.0g,0.1g,"4 skinless salmon fillets, 1 tbsp olive oil or..."
4,https://www.bbcgoodfood.com/recipes/bean-hallo...,Bean Halloumi Stew,468.0,25.0g,7.0g,36g,12.0g,14.0g,19.0g,1.9g,"3 tbsp olive oil, 1 onion thinly sliced, 1 red..."

In [ ]:
# Install dependencies (if not already)
# !pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# -----------------------------
# Configuration
# -----------------------------
BASE_URL = "https://www.bbcgoodfood.com"
COLLECTION_URL = "https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

# -----------------------------
# Functions
# -----------------------------
def get_recipe_links(collection_url):
    """Get all recipe links from a collection page."""
    links = []
    page = 1
    while True:
        url = f"{collection_url}?page={page}"
        print(f"Fetching collection page {page}: {url}")
        res = requests.get(url, headers=headers)
        if res.status_code != 200:
            print("No more pages or failed to fetch collection.")
            break
        soup = BeautifulSoup(res.text, "html.parser")
        recipe_cards = soup.find_all("div", class_="card__section card__content")
        if not recipe_cards:
            break  # No more recipes found
        for card in recipe_cards:
            a_tag = card.find("a", class_="link d-block")
            if a_tag and a_tag.get('href'):
                href = a_tag['href']
                if "/recipes/" in href:
                    if href.startswith("http"):
                        links.append(href)
                    else:
                        links.append(BASE_URL + href)
        page += 1
        time.sleep(1)
    return links

def scrape_recipe(recipe_url):
    """Scrape a single recipe page for title, ingredients, and nutrition info."""
    print(f"Scraping recipe: {recipe_url}")
    res = requests.get(recipe_url, headers=headers)
    soup = BeautifulSoup(res.text, "html.parser")
    
    # Title
    title_tag = soup.find("h1", class_="post-header__title")
    title = title_tag.text.strip() if title_tag else "No title"
    
    # Ingredients
    ingredients = []
    tabbed_div = soup.find("div", class_="tabbed-list__content")
    if tabbed_div:
        ul_list = tabbed_div.find("ul", class_="ingredients-list")
        if ul_list:
            for li in ul_list.find_all("li", class_="ingredients-list__item"):
                qty_tag = li.find("span", class_="ingredients-list__item-quantity")
                ing_tag = li.find("span", class_="ingredients-list__item-ingredient")
                note_tag = li.find("div", class_="ingredients-list__item-note")
                qty = qty_tag.text.strip() if qty_tag else ""
                ingredient = ing_tag.text.strip() if ing_tag else ""
                note = note_tag.text.strip() if note_tag else ""
                ingredients.append({"quantity": qty, "ingredient": ingredient, "note": note})
    
    # Nutrition
    nutrition = {}
    nutrition_list = soup.find("ul", class_="nutrition-list")
    if nutrition_list:
        for li in nutrition_list.find_all("li", class_="nutrition-list__item"):
            label_tag = li.find("span", class_="nutrition-list__label")
            if label_tag:
                label = label_tag.text.strip()
                value = li.get_text(separator="|").split("|")[1].strip() if "|" in li.get_text(separator="|") else ""
                nutrition[label] = value
    
    return {"title": title, "url": recipe_url, "ingredients": ingredients, "nutrition": nutrition}

def scrape_collection(collection_url):
    """Scrape all recipes from a collection."""
    recipe_links = get_recipe_links(collection_url)
    print(f"Found {len(recipe_links)} recipe links.")
    all_recipes = []
    for idx, link in enumerate(recipe_links, 1):
        try:
            recipe_data = scrape_recipe(link)
            all_recipes.append(recipe_data)
            time.sleep(1)
        except Exception as e:
            print(f"Failed to scrape {link}: {e}")
    return all_recipes

# -----------------------------
# Run the scraper
# -----------------------------
recipes = scrape_collection(COLLECTION_URL)

# -----------------------------
# Save to CSV
# -----------------------------
data_for_csv = []
for r in recipes:
    for ing in r['ingredients']:
        data_for_csv.append({
            "title": r['title'],
            "url": r['url'],
            "ingredient": ing['ingredient'],
            "quantity": ing['quantity'],
            "note": ing['note'],
            **r['nutrition']
        })

df = pd.DataFrame(data_for_csv)
df.to_csv(r"breakfast_recipes.csv", index=False)
print("Scraping complete! Data saved to breakfast.csv")

Fetching collection page 1: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=1
Fetching collection page 2: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=2
Fetching collection page 3: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=3
Fetching collection page 4: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=4
Fetching collection page 5: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=5
Fetching collection page 6: https://www.bbcgoodfood.com/recipes/collection/breakfast-recipes?page=6
No more pages or failed to fetch collection.
Found 96 recipe links.
Scraping recipe: https://www.bbcgoodfood.com/recipes/american-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/the-breakfast-club
Scraping recipe: https://www.bbcgoodfood.com/recipes/pain-au-chocolat
Scraping recipe: https://www.bbcgoodfood.com/recipes/leek-kale-hash-with-sage-fried-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/baby-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/protein-porridge
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheese-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/eggs-florentine
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-bloody-mary-eggs-with-crunchy-croutons
Scraping recipe: https://www.bbcgoodfood.com/recipes/protein-pancakes-with-banana
Scraping recipe: https://www.bbcgoodfood.com/recipes/smashed-peas-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/langos
Scraping recipe: https://www.bbcgoodfood.com/recipes/poached-eggs-smoked-salmon-and-bubble-squeak
Scraping recipe: https://www.bbcgoodfood.com/recipes/potato-fritters
Scraping recipe: https://www.bbcgoodfood.com/recipes/rhubarb-custard-fluffy-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/english-muffins
Scraping recipe: https://www.bbcgoodfood.com/recipes/fried-bread
Scraping recipe: https://www.bbcgoodfood.com/recipes/peanut-butter-stuffed-french-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-fry-up
Scraping recipe: https://www.bbcgoodfood.com/recipes/breakfast-hash
Scraping recipe: https://www.bbcgoodfood.com/recipes/chocolate-orange-french-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/next-level-kedgeree
Scraping recipe: https://www.bbcgoodfood.com/recipes/family-breakfast-station
Scraping recipe: https://www.bbcgoodfood.com/recipes/pancake-breakfast-tacos
Scraping recipe: https://www.bbcgoodfood.com/recipes/overnight-oats
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-bacon
Scraping recipe: https://www.bbcgoodfood.com/recipes/poached-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-beans-baked-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/classic-baked-oats
Scraping recipe: https://www.bbcgoodfood.com/recipes/perfect-scrambled-eggs-recipe
Scraping recipe: https://www.bbcgoodfood.com/recipes/turbo-beans-cheese-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-pancakes-two-ways
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-egg-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/panettone-french-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/banana-blueberry-muffins
Scraping recipe: https://www.bbcgoodfood.com/recipes/carrot-cake-porridge
Scraping recipe: https://www.bbcgoodfood.com/recipes/classic-waffles
Scraping recipe: https://www.bbcgoodfood.com/recipes/one-pan-eggs-peppers
Scraping recipe: https://www.bbcgoodfood.com/recipes/blueberry-banana-power-smoothie
Scraping recipe: https://www.bbcgoodfood.com/recipes/soft-boiled-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/eggy-cheese-crumpets
Scraping recipe: https://www.bbcgoodfood.com/recipes/banana-oat-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/pancetta-pepper-piperade
Scraping recipe: https://www.bbcgoodfood.com/recipes/chorizo-sweet-potato-breakfast-tortillas
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-breakfast-burritos
Scraping recipe: https://www.bbcgoodfood.com/recipes/chocolate-porridge
Scraping recipe: https://www.bbcgoodfood.com/recipes/salted-caramel-cheesecake-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/breakfast-casserole
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-banana-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/egg-hole-smoked-salmon-avocado-toastie
Scraping recipe: https://www.bbcgoodfood.com/recipes/good-you-granola
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheesy-skillet-hash-brown-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/middle-eastern-eggs-merguez-pistachios
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-egg-muffins
Scraping recipe: https://www.bbcgoodfood.com/recipes/ham-potato-hash-baked-beans-healthy-fried-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/matcha-miso-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/chai-spiced-apple-sultana-porridge-topper
Scraping recipe: https://www.bbcgoodfood.com/recipes/tropical-breakfast-bars
Scraping recipe: https://www.bbcgoodfood.com/recipes/big-breakfast-courgette-potato-rosti
Scraping recipe: https://www.bbcgoodfood.com/recipes/brioche-breakfast-bake-crispy-bacon
Scraping recipe: https://www.bbcgoodfood.com/recipes/blackberry-white-chocolate-porridge-topper
Scraping recipe: https://www.bbcgoodfood.com/recipes/baked-green-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/shakshuka
Scraping recipe: https://www.bbcgoodfood.com/recipes/hash-browns-gruyere-pancetta
Scraping recipe: https://www.bbcgoodfood.com/recipes/mushroom-croque-monsieur-rolls
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-moroccan-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/avocado-toast-chorizo-fried-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/oven-baked-egg-chips
Scraping recipe: https://www.bbcgoodfood.com/recipes/parsnip-hash-browns
Scraping recipe: https://www.bbcgoodfood.com/recipes/full-english-potato-cake
Scraping recipe: https://www.bbcgoodfood.com/recipes/sausage-egg-baps-spicy-tomato-sauce
Scraping recipe: https://www.bbcgoodfood.com/recipes/spinach-baked-eggs-parmesan-tomato-toasts
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-breakfast-bakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/healthy-egg-chips
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-bean-bacon-eggy-bread-bake
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-vegan-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/full-english-frittata-smoky-beans
Scraping recipe: https://www.bbcgoodfood.com/recipes/eggs-benedict-smoked-salmon-chives
Scraping recipe: https://www.bbcgoodfood.com/recipes/banana-overnight-oats
Scraping recipe: https://www.bbcgoodfood.com/recipes/pancakes-one
Scraping recipe: https://www.bbcgoodfood.com/recipes/honey-mustard-sausages-tomatoes-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/dippy-eggs-marmite-soldiers
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheesy-french-toast-ham-grilled-vine-tomatoes
Scraping recipe: https://www.bbcgoodfood.com/recipes/mushroom-hash-poached-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/green-spirulina-smoothie
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-protein-pancakes
Scraping recipe: https://www.bbcgoodfood.com/recipes/orange-dark-chocolate-yogurt-bowls
Scraping recipe: https://www.bbcgoodfood.com/recipes/baked-eggs-with-spinach-tomatoes-ricotta-basil
Scraping recipe: https://www.bbcgoodfood.com/recipes/breakfast-pancake-platter
Scraping recipe: https://www.bbcgoodfood.com/recipes/ginger-vanilla-pears-porridge-topper
Scraping recipe: https://www.bbcgoodfood.com/recipes/puff-pastry-cinnamon-rolls
Scraping recipe: https://www.bbcgoodfood.com/recipes/salsa-verde-baked-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/vanilla-cinnamon-breakfast-rice
Scraping recipe: https://www.bbcgoodfood.com/recipes/potato-scones-with-smoked-salmon-soured-cream
Scraping recipe: https://www.bbcgoodfood.com/recipes/sticky-malt-loaves
Scraping complete! Data saved to breakfast.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"breakfast_recipes.csv")

df.head()

df["title"] = (
    df["url"]
    .str.split("/")
    .str[-1]
    .str.replace("-", " ")
    .str.title()
)

df[["title","url"]].head()

df["ingredient_full"] = (
    df["quantity"].fillna("") + " " +
    df["ingredient"].fillna("") + " " +
    df["note"].fillna("")
).str.strip()

ingredients_grouped = (
    df.groupby("url")["ingredient_full"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

ingredients_grouped.head()

nutrition_cols = [
    "kcal","fat","saturates","carbs",
    "sugars","fibre","protein","salt"
]

recipes = (
    df.groupby("url")
    .first()
    .reset_index()[["url","title"] + nutrition_cols]
)

recipes.head()

clean_df = recipes.merge(
    ingredients_grouped,
    on="url",
    how="left"
)

clean_df.head()

clean_df = clean_df.rename(columns={
    "ingredient_full":"ingredients"
})

cols = ["fat","saturates","carbs","sugars","fibre","protein","salt"]

for col in cols:
    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(r'(low|medium|high)', '', regex=True)  # remove labels
        .str.extract(r'([\d\.]+)')[0]                       # keep number
        .fillna('')
        + "g"                                               # add grams back
    )
    # Chat wrote this code for cleaning the dataset (title uses the last words of the url, ingredients combines quantity, ingredient and note
    # nutrition removes low/medium/high labels and keeps only numbers with 'g' unit for grams (remove random words like 16glow instead of 16g ))
clean_df.to_csv("breakfast_recipes.csv", index=False)
clean_df.head()

,url,title,kcal,fat,saturates,carbs,sugars,fibre,protein,salt,ingredients
0,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Bacon,74,6g,2.0g,0.0g,0.0g,0.0g,6.0g,0.88g,6 rashers streaky bacon or 3 rashers back bacon
1,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Fry Up,845,44g,14.0g,61.0g,7.0g,9.0g,47.0g,4.1g,"1 English muffin, ½ tsp butter softened, 200g ..."
2,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Omelette,251,22g,10.0g,0.1g,0.1g,0.0g,13.0g,0.68g,"15g butter, 2 eggs, fillings of your choice, s..."
3,https://www.bbcgoodfood.com/recipes/american-p...,American Pancakes,356,13g,6.0g,46.0g,8.0g,2.0g,13.0g,1.3g,"200g self-raising flour, 1 ½ tsp baking powder..."
4,https://www.bbcgoodfood.com/recipes/avocado-to...,Avocado Toast Chorizo Fried Eggs,522,37g,10.0g,25.0g,3.0g,4.0g,23.0g,1.5g,"1 tbsp pumpkin seed, 85g chorizo sliced into c..."

In [ ]:
# Install dependencies (if not already)
# !pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

# -----------------------------
# Configuration
# -----------------------------
BASE_URL = "https://www.bbcgoodfood.com"
COLLECTION_URL = "https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

# -----------------------------
# Functions
# -----------------------------
def get_recipe_links(collection_url):
    """Get all recipe links from a collection page."""
    links = []
    page = 1
    while True:
        url = f"{collection_url}?page={page}"
        print(f"Fetching collection page {page}: {url}")
        res = requests.get(url, headers=headers)
        if res.status_code != 200:
            print("No more pages or failed to fetch collection.")
            break
        soup = BeautifulSoup(res.text, "html.parser")
        recipe_cards = soup.find_all("div", class_="card__section card__content")
        if not recipe_cards:
            break  # No more recipes found
        for card in recipe_cards:
            a_tag = card.find("a", class_="link d-block")
            if a_tag and a_tag.get('href'):
                href = a_tag['href']
                if "/recipes/" in href:
                    if href.startswith("http"):
                        links.append(href)
                    else:
                        links.append(BASE_URL + href)
        page += 1
        time.sleep(1)
    return links

def scrape_recipe(recipe_url):
    """Scrape a single recipe page for title, ingredients, and nutrition info."""
    print(f"Scraping recipe: {recipe_url}")
    res = requests.get(recipe_url, headers=headers)
    soup = BeautifulSoup(res.text, "html.parser")
    
    # Title
    title_tag = soup.find("h1", class_="post-header__title")
    title = title_tag.text.strip() if title_tag else "No title"
    
    # Ingredients
    ingredients = []
    tabbed_div = soup.find("div", class_="tabbed-list__content")
    if tabbed_div:
        ul_list = tabbed_div.find("ul", class_="ingredients-list")
        if ul_list:
            for li in ul_list.find_all("li", class_="ingredients-list__item"):
                qty_tag = li.find("span", class_="ingredients-list__item-quantity")
                ing_tag = li.find("span", class_="ingredients-list__item-ingredient")
                note_tag = li.find("div", class_="ingredients-list__item-note")
                qty = qty_tag.text.strip() if qty_tag else ""
                ingredient = ing_tag.text.strip() if ing_tag else ""
                note = note_tag.text.strip() if note_tag else ""
                ingredients.append({"quantity": qty, "ingredient": ingredient, "note": note})
    
    # Nutrition
    nutrition = {}
    nutrition_list = soup.find("ul", class_="nutrition-list")
    if nutrition_list:
        for li in nutrition_list.find_all("li", class_="nutrition-list__item"):
            label_tag = li.find("span", class_="nutrition-list__label")
            if label_tag:
                label = label_tag.text.strip()
                value = li.get_text(separator="|").split("|")[1].strip() if "|" in li.get_text(separator="|") else ""
                nutrition[label] = value
    
    return {"title": title, "url": recipe_url, "ingredients": ingredients, "nutrition": nutrition}

def scrape_collection(collection_url):
    """Scrape all recipes from a collection."""
    recipe_links = get_recipe_links(collection_url)
    print(f"Found {len(recipe_links)} recipe links.")
    all_recipes = []
    for idx, link in enumerate(recipe_links, 1):
        try:
            recipe_data = scrape_recipe(link)
            all_recipes.append(recipe_data)
            time.sleep(1)
        except Exception as e:
            print(f"Failed to scrape {link}: {e}")
    return all_recipes

# -----------------------------
# Run the scraper
# -----------------------------
recipes = scrape_collection(COLLECTION_URL)

# -----------------------------
# Save to CSV
# -----------------------------
data_for_csv = []
for r in recipes:
    for ing in r['ingredients']:
        data_for_csv.append({
            "title": r['title'],
            "url": r['url'],
            "ingredient": ing['ingredient'],
            "quantity": ing['quantity'],
            "note": ing['note'],
            **r['nutrition']
        })

df = pd.DataFrame(data_for_csv)
df.to_csv(r"lunch_recipes.csv", index=False)
print("Scraping complete! Data saved to lunch_recipes.csv")

Fetching collection page 1: https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes?page=1
Fetching collection page 2: https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes?page=2
Fetching collection page 3: https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes?page=3
Fetching collection page 4: https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes?page=4
Fetching collection page 5: https://www.bbcgoodfood.com/recipes/collection/quick-lunch-recipes?page=5
No more pages or failed to fetch collection.
Found 76 recipe links.
Scraping recipe: https://www.bbcgoodfood.com/recipes/falafel-burgers-0
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-chicken-hummus-bowl
Scraping recipe: https://www.bbcgoodfood.com/recipes/10minute-couscous-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/smashed-peas-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-chicken-avocado-wraps
Scraping recipe: https://www.bbcgoodfood.com/recipes/shake-it-up-chopped-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/bulgur-quinoa-lunch-bowls
Scraping recipe: https://www.bbcgoodfood.com/recipes/quick-spicy-nasi-goreng
Scraping recipe: https://www.bbcgoodfood.com/recipes/kimchi-double-cheese-toasties
Scraping recipe: https://www.bbcgoodfood.com/recipes/storecupboard-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/mortadella-burrata-pistachio-pesto-ciabatta
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoked-salmon-quinoa-dill-lunch-pot
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-ham-cheese-egg-bagel
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-tuna-wrap
Scraping recipe: https://www.bbcgoodfood.com/recipes/pearl-couscous-salad-with-hot-smoked-trout-buttermilk-dressing
Scraping recipe: https://www.bbcgoodfood.com/recipes/caesar-salad-wrap
Scraping recipe: https://www.bbcgoodfood.com/recipes/green-chicken-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/basa-fillet-with-garlic-spring-onion-paprika-butter
Scraping recipe: https://www.bbcgoodfood.com/recipes/classic-chicken-ramen
Scraping recipe: https://www.bbcgoodfood.com/recipes/baked-feta-bean-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-fish-dip-bagel-chips
Scraping recipe: https://www.bbcgoodfood.com/recipes/orzo-feta-prawn-pasta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/egg-avocado-open-sandwich
Scraping recipe: https://www.bbcgoodfood.com/recipes/beef-red-chimichurri-quinoa
Scraping recipe: https://www.bbcgoodfood.com/recipes/halloumi-carrot-orange-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/storecupboard-saucy-pasta-chickpeas
Scraping recipe: https://www.bbcgoodfood.com/recipes/chorizo-chickpea-soup
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-mango-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/creamy-miso-beans-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-pesto-wrap
Scraping recipe: https://www.bbcgoodfood.com/recipes/broccoli-pasta-salad-eggs-sunflower-seeds
Scraping recipe: https://www.bbcgoodfood.com/recipes/healthy-beef-chow-mein
Scraping recipe: https://www.bbcgoodfood.com/recipes/ultimate-chorizo-ciabatta
Scraping recipe: https://www.bbcgoodfood.com/recipes/veggie-noodle-pot
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-kiev-quesadilla
Scraping recipe: https://www.bbcgoodfood.com/recipes/italian-sub
Scraping recipe: https://www.bbcgoodfood.com/recipes/caesar-pitta
Scraping recipe: https://www.bbcgoodfood.com/recipes/fish-finger-wraps-pea-puree
Scraping recipe: https://www.bbcgoodfood.com/recipes/green-baked-eggs
Scraping recipe: https://www.bbcgoodfood.com/recipes/zingy-grapefruit-prawn-avocado-tamarind-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/feta-semi-dried-tomato-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-lime-mixed-bean-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/beetroot-humous-toasts-olives-mint
Scraping recipe: https://www.bbcgoodfood.com/recipes/lemony-tuna-asparagus-salad-box
Scraping recipe: https://www.bbcgoodfood.com/recipes/citrussy-tofu-udon-shake-up-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/curried-pork-bulghar-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/tuna-asparagus-white-bean-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/sesame-chicken-noodles
Scraping recipe: https://www.bbcgoodfood.com/recipes/coronation-chicken-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/keep-it-green-sandwich
Scraping recipe: https://www.bbcgoodfood.com/recipes/deli-couscous
Scraping recipe: https://www.bbcgoodfood.com/recipes/little-gem-griddled-courgette-feta-shake-up-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-cucumber-watermelon-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/vermicelli-noodle-beef-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/prawn-sugar-snap-pea-feta-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/tuna-salad-sandwich
Scraping recipe: https://www.bbcgoodfood.com/recipes/pastrami-sandwich
Scraping recipe: https://www.bbcgoodfood.com/recipes/chicken-rice-bowl
Scraping recipe: https://www.bbcgoodfood.com/recipes/spicy-bean-avocado-quesadillas
Scraping recipe: https://www.bbcgoodfood.com/recipes/cheese-omelette
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-mushrooms-on-toast
Scraping recipe: https://www.bbcgoodfood.com/recipes/air-fryer-cheese-ham-toastie
Scraping recipe: https://www.bbcgoodfood.com/recipes/smoky-chickpea-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/kale-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/buddha-bowl-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/marinated-tomato-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/herby-courgette-white-bean-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/easy-green-gazpacho
Scraping recipe: https://www.bbcgoodfood.com/recipes/tomato-black-bean-taco-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/blue-cheese-ham-egg-toastie
Scraping recipe: https://www.bbcgoodfood.com/recipes/turkish-egg-flatbreads
Scraping recipe: https://www.bbcgoodfood.com/recipes/garlic-mushrooms
Scraping recipe: https://www.bbcgoodfood.com/recipes/vegetarian-ramen
Scraping recipe: https://www.bbcgoodfood.com/recipes/lentil-tuna-salad
Scraping recipe: https://www.bbcgoodfood.com/recipes/healthy-coleslaw
Scraping complete! Data saved to lunch_recipes.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"lunch_recipes.csv")

df.head()

df["title"] = (
    df["url"]
    .str.split("/")
    .str[-1]
    .str.replace("-", " ")
    .str.title()
)

df[["title","url"]].head()

df["ingredient_full"] = (
    df["quantity"].fillna("") + " " +
    df["ingredient"].fillna("") + " " +
    df["note"].fillna("")
).str.strip()

ingredients_grouped = (
    df.groupby("url")["ingredient_full"]
    .apply(lambda x: ", ".join(x))
    .reset_index()
)

ingredients_grouped.head()

nutrition_cols = [
    "kcal","fat","saturates","carbs",
    "sugars","fibre","protein","salt"
]

recipes = (
    df.groupby("url")
    .first()
    .reset_index()[["url","title"] + nutrition_cols]
)

recipes.head()

clean_df = recipes.merge(
    ingredients_grouped,
    on="url",
    how="left"
)

clean_df.head()

clean_df = clean_df.rename(columns={
    "ingredient_full":"ingredients"
})

cols = ["fat","saturates","carbs","sugars","fibre","protein","salt"]

for col in cols:
    clean_df[col] = (
        clean_df[col]
        .astype(str)
        .str.replace(r'(low|medium|high)', '', regex=True)  # remove labels
        .str.extract(r'([\d\.]+)')[0]                       # keep number
        .fillna('')
        + "g"                                               # add grams back
    )
    # Chat wrote this code for cleaning the dataset (title uses the last words of the url, ingredients combines quantity, ingredient and note
    # nutrition removes low/medium/high labels and keeps only numbers with 'g' unit for grams (remove random words like 16glow instead of 16g ))
clean_df.to_csv("lunch_recipes.csv", index=False)
clean_df.head()

,url,title,kcal,fat,saturates,carbs,sugars,fibre,protein,salt,ingredients
0,https://www.bbcgoodfood.com/recipes/10minute-c...,10Minute Couscous Salad,468,24g,5g,44.0g,7.0g,5g,16g,1.23g,"100g couscous, 200ml hot low salt vegetable st..."
1,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Cheese Ham Toastie,627,38g,22g,43.0g,3.0g,5g,27g,2.88g,"20g butter softened, 2 slices sourdough or oth..."
2,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Ham Cheese Egg Bagel,505,17g,7g,56.0g,13.0g,2g,30g,2.7g,"1 bagel halved, ½ tbsp chilli jam or red onion..."
3,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Mushrooms On Toast,349,8g,1g,53.0g,4.0g,4g,15g,1.6g,"300g chestnut mushrooms quartered or sliced, a..."
4,https://www.bbcgoodfood.com/recipes/air-fryer-...,Air Fryer Omelette,251,22g,10g,0.1g,0.1g,0g,13g,0.68g,"15g butter, 2 eggs, fillings of your choice, s..."